### ISSUE TITLE
Expand basic build to include a dropdown course filter

### ISSUE THREAD

**Issue by justin0022** [UBC-LA-Hackathon/student-dashboard#1]
Heatmap should display discussion from course selected.

There will also need to be a new `Tasks` readme created, probably between step 4 and 5.

**Comment by justin0022** [comment]
@markoprodanovic I'm happy to help with this, just push your branch early and we can collaborate!

**Comment by markoprodanovic** [comment]
@justin0022 should we be pushing an **implementation** of the dropdown feature to this branch? This won't end up in our actual code-base right, just for us?

**Comment by justin0022** [comment]
We shouldn't be pushing the implementation, because we don't want the actual implementation to be public. I'd recommend you create a private repo, then push a copy of this repo to your private repo, and build the implementation there, if you need to build it. 

If we don't want to actually implement the code (and therefore not provide many actual code snippets), then we can just write up the general steps.

**Comment by justin0022** [comment]
I meant to create a branch for adding the steps required, not for implementing the actual code. Although if we want to provide some code snippets to make it a little easier, then we can push the code to this branch!

**Comment by markoprodanovic** [comment]
Gotcha, thanks for the clarification! Will create a private repo to get a better sense of a _possible_ implementation, but will only push general steps here.

**Comment by justin0022** [comment]
Perfect, that's exactly what I've been doing. Kind of a pain to maintain tbh, since you can't make PRs from private repos to public repos (which makes sense), but it's been working out okay so far. Let me know if you need help with anything!

**Comment by justin0022** [comment]
@markoprodanovic could we prioritize this? I know your implementation is basically finished now, so we should start working on the documentation changes. Happy to help, let me know how you want to divide/conquer.

**Comment by markoprodanovic** [comment]
@justin0022 for sure! For documentation we're thinking write-ups like the ones currently in the **_ideas** folder?
Also we're classifying both dropdown menu and caching are **intermediate** tasks right?

**Comment by justin0022** [comment]
> @justin0022 for sure! For documentation we're thinking write-ups like the ones currently in the **_ideas** folder?

I don't think so, I think we're going to add them to the actual Tasks.

**Comment by justin0022** [comment]
> Also we're classifying both dropdown menu and caching are **intermediate** tasks right?

The dropdown will be part of the build and the caching/loading state is intermediate?

**Comment by justin0022** [comment]
> I don't think so, I think we're going to add them to the actual Tasks.

<img width="668" alt="Screen Shot 2020-02-27 at 12 10 05 PM" src="https://user-images.githubusercontent.com/8836578/75482664-1efc4780-595a-11ea-8440-f8d690b24b14.png">

Specifically I was thinking a step in between 4-5, maybe a `Create a dropdown to switch between your classes`.

**Comment by markoprodanovic** [comment]
Oh riiight. Now remembering we talked about making the dropdown a core task.
Ya I'll be working on that documentation this afternoon!

Caching/loading probably make sense in intermediate.

**Comment by justin0022** [comment]
Okay great, create a new branch and I'll collaborate with you on it

**Comment by markoprodanovic** [comment]
👍 check out the **course-dropdown-documentation** branch (nothing interesting on there yet I'll ping you once I push some stuff)
