### ISSUE TITLE
Create explanation of data for the CSV/JSON

### ISSUE THREAD

**Issue by justin0022** [UBC-LA-Hackathon/student-dashboard#30]
Columns and what they mean.

**Comment by justin0022** [comment]
@alisonmyers do you mind taking this on? @craigdsthompson can send you the data (if he's received it yet).

**Comment by alisonmyers** [comment]
Can do.

**Comment by justin0022** [comment]
@alisonmyers I'll send you the data shortly about this

**Comment by alisonmyers** [comment]
done
